# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: internal-production
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['internal.metrics.thenewgym.vn']