services:
  verdaccio:
    image: verdaccio/verdaccio:nightly-master
    container_name: npm-package
    environment: 
      - VERDACCIO_PUBLIC_URL=https://registry.thenewtech.vn
    user: root
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
volumes:
  verdaccio:
    driver: local