const GENERAL_MESSAGE_PATTERN = 'general-message-pattern';
const MESSAGE_RESPONSE = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_GATEWAY: 'BAD_GATEWAY',
  BAD_REQUEST: 'BAD_REQUEST',
};

export { GENERAL_MESSAGE_PATTERN, MESSAGE_RESPONSE };
