const ACTION = {
  GET_BY_IDS: 'GET_BY_IDS',
  GET_ONE: 'GET_ONE',
  GET_LIST: 'GET_LIST',
  GET_LIST_PAGING: 'GET_LIST_PAGING',
  STORE: 'STORE',
  UPDATE: 'UPDATE',
  STORE_ARRAY: 'STORE_ARRAY',
};
const GENERAL_MESSAGE_PATTERN = 'general-message-pattern';

export { ACTION, GENERAL_MESSAGE_PATTERN };
