name: "🚀 Publish"

on:
    pull_request:
      branches: 
        - aws-prod
      types: [closed]
jobs:
    build_publish:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:

        # Setup node version, npm version
        - uses: actions/checkout@v3
        - name: 🟢 node
          uses: actions/setup-node@v3
          with:
            node-version: 14.17.0
            npm-version: 6.14.13
            registry-url: https://npm.pkg.github.com/

        # Get file changes
        - id: file_changes
          name: File Changes
          uses: trilom/file-changes-action@v1.2.4

        # Publish consumer-gw
        - name: Publish consumer-gw
          if: contains(steps.file_changes.outputs.files , 'consumer-gateway/')
          working-directory: ./packages/consumer-gateway
          run: |
              echo === build consumer-gw ====
              npm -v
              npm i
              npm run build
              npm publish
          env:
              NODE_AUTH_TOKEN: ${{secrets.TP_ACCESS_TOKEN}}

        # Publish consumer-sv
        - name: Publish consumer-sv
          if: contains(steps.file_changes.outputs.files , 'consumer-service/')
          working-directory: ./packages/consumer-service
          run: |
              echo === build consumer-sv ====
              npm -v
              npm i
              npm run build
              npm publish
          env:
              NODE_AUTH_TOKEN: ${{secrets.TP_ACCESS_TOKEN}}

        # Publish entities
        - name: Publish entities
          if: contains(steps.file_changes.outputs.files , 'entities/')
          working-directory: ./packages/entities
          run: |
              echo === build entities ====
              npm -v
              npm i
              npm run build
              npm publish
          env:
              NODE_AUTH_TOKEN: ${{secrets.TP_ACCESS_TOKEN}}